Feat: support new resolving import at-rules
microsoft/vscode-css-languageservice pull request #255
Opened 2021-10-27 04:31 UTC by fyangstudio

https://github.com/webpack-contrib/sass-loader#resolving-import-at-rules

> Using `~` is deprecated and can be removed from your code (we recommend it), but we still support it for historical reasons. Why can you remove it? The loader will first try to resolve @import as a relative path. If it cannot be resolved, then the loader will try to resolve @import inside `node_modules`.

Support VS Code DefinitionProvider find right package like:

```scss
@import "bootstrap";
@import "~bootstrap";
```

2021-11-24 02:37 UTC, fyangstudio commented
@aeschli

2021-11-24 07:13 UTC, aeschli commented
> The loader will first try to resolve @import as a relative path. If it cannot be resolved, then the loader will try to resolve @import inside node_modules

The looking up of an import in node_modules, Is this something webpack does, or SCSS?

2021-11-25 03:37 UTC, fyangstudio commented
> > The loader will first try to resolve @import as a relative path. If it cannot be resolved, then the loader will try to resolve @import inside node_modules
> 
> The looking up of an import in node_modules, Is this something webpack does, or SCSS?

Webpack and Sass are both mentioned that imports will always be resolved relative to the current file first, see: 

Webpack: https://github.com/webpack-contrib/sass-loader#resolving-import-at-rules
Sass: https://sass-lang.com/documentation/at-rules/import#load-paths

This PR support node module resolution without `~`. 

PS: using `~` is work too

2021-11-29 09:24 UTC, fyangstudio commented
> > The loader will first try to resolve @import as a relative path. If it cannot be resolved, then the loader will try to resolve @import inside node_modules
> 
> The looking up of an import in node_modules, Is this something webpack does, or SCSS?

@aeschli   Webpack and Sass are both mentioned that imports will always be resolved relative to the current file first, see: 

Webpack: https://github.com/webpack-contrib/sass-loader#resolving-import-at-rules
Sass: https://sass-lang.com/documentation/at-rules/import#load-paths

This PR support node module resolution without `~`. 

PS: using `~` is work too

2021-11-29 10:13 UTC, aeschli commented
Thanks @fyangstudio.
I wonder if we should only enable this for SCSS. Right now, that change would enable the extended resolving also for LESS and CSS.
For CSS there's the [css-loader](https://github.com/webpack-contrib/css-loader#url). If I get this right, it still requires '~'.

Also, it would be nice to have tests as well.

2021-11-29 12:11 UTC, aeschli requested changes

2021-11-29 12:11 UTC, aeschli commented on src/services/cssNavigation.ts
> +		if (relativeReference) {
This is always true. documentContext.resolveReference just computes a URI, but does not make an existence test.

2021-11-30 03:26 UTC, fyangstudio commented
> Thanks @fyangstudio. I wonder if we should only enable this for SCSS. Right now, that change would enable the extended resolving also for LESS and CSS. For CSS there's the [css-loader](https://github.com/webpack-contrib/css-loader#url). If I get this right, it still requires '~'.
> 
> Also, it would be nice to have tests as well.

@aeschli   '~' is deprecated in Less too,  https://webpack.js.org/loaders/less-loader/ .

I think css-loader will support the new resolving import at-rules soon.

2021-11-30 07:13 UTC, fyangstudio commented
> Thanks @fyangstudio. I wonder if we should only enable this for SCSS. Right now, that change would enable the extended resolving also for LESS and CSS. For CSS there's the [css-loader](https://github.com/webpack-contrib/css-loader#url). If I get this right, it still requires '~'.
> 
> Also, it would be nice to have tests as well.

'~' is deprecated in Less too,  https://webpack.js.org/loaders/less-loader/#webpack-resolver 

I change it only enable new rule for Sass and Less,  @aeschli  please check.

By the way I think css-loader will support the new resolving import at-rules soon.

2021-12-09 02:36 UTC, fyangstudio commented
@aeschli if this PR have any questions, please let me know.

2021-12-09 11:08 UTC, aeschli commented
I polished the check whether to resolve module references (https://github.com/microsoft/vscode-css-languageservice/pull/255/commits/6e64249552bd96049f92e174d6ff7d7c35a7354b)

All looks good now, thanks @fyangstudio !

2021-12-09 11:08 UTC, aeschli approved these changes

2021-12-09 11:08 UTC, merged